// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GeneratePassword(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GeneratePassword'](arg1, arg2, arg3, arg4);
}

export function Shutdown(arg1) {
  return window['go']['app']['App']['Shutdown'](arg1);
}

export function TestMessage() {
  return window['go']['app']['App']['TestMessage']();
}
