// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function GeneratePassword(arg1:number,arg2:boolean,arg3:boolean,arg4:boolean):Promise<string>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function TestMessage():Promise<string>;
